### ISSUE TITLE
Quest module mistakenly activating other quests

### ISSUE THREAD

**Issue by silfumus** [mrmin123/kancolle-auto#112]
Let say that I have the following line in config.ini, **Quests: d2, d3, d4, d9, d11**

For some reason, kancolle-auto keeps activating other quests (e.g: F12 and other sortie quests). On accounts with limited quests it might be fine. But for those with many uncleared quests, it might took 2 out of 5 quests slot, which is unacceptable.

Is it a known problem or am I doing something incorrectly?

I was thinking of either increase the image sensitivity or supplying sikuli with better images, but thought it would better to consult here first.

**Comment by mrmin123** [comment]
No, it does keep activating the wrong quests despite having the image match parameter set to100%. I think I've provided it the best images possible while remaining browser/viewer-independent (aka no text shown, since that differs across viewers and settings), and haven't come up with a solution yet. If you have any ideas please let me know.

**Comment by silfumus** [comment]
The only solution I can think of is providing option on config.ini and another set of quest images.
Example in config.ini:

```
# Set to True if you want kancolle-auto to use the alternative set of quest images which
# improves kancolle-auto ability to choose the correct quests.
# Default to False for viewers with quest UI translations enabled and compatibility reason.
EnableAlternativeQuestImage = False
```

Cant speak for others, but I would gladly have the quest UI translations disabled rather than having kancolle-auto pick the wrong quests.

**Comment by mrmin123** [comment]
I don't want to say it, but yes, I think that might be the only way. I just don't think it's possible to stay viewer-independent while having accurate quest selections.

Back to taking screenshots of the quests screen I guess!

**Comment by mrmin123** [comment]
@silfumus Actually, do you know which quests are being activated in lieu of which quests?

**Comment by silfumus** [comment]
I don't have the specifics, but assuming the default config with combat and expedition turned on:
Bm2, B44, (and probably) B58.

Edit: Bm2 is activated because of bd6.

**Comment by mrmin123** [comment]
Conflicts I've run into so far:
- Bm2 (0 / 200 / 0 / 0) activated by Bd6 (0 / 600 / 0 / 0)
- B46 (0 / 300 / 0 / 400) activated by Bw2 (0 / 500 / 0 / 500)

Need to figure out why these non-exact matches are being hit by Sikuli.

**Comment by mrmin123** [comment]
Apparently `.exact()` is bugged: https://answers.launchpad.net/sikuli/+question/124710

Changing `.exact()` to `.similar(0.99)` did not fix it for the Quest module, but `.similar(0.999)` fixed it. Fixed in latest master.

edit: kind of worried about the implications this has wherever else `exact()` is used, but if it ain't broke...
