### ISSUE TITLE
SubmarineSwitch sortieing lv1 Taigei

### ISSUE THREAD

**Issue by silfumus** [mrmin123/kancolle-auto#115]
Apparently kancolle-auto were switching I-168 Kai (after taiha) with lv1 Taigei.
Can't remember the specifics, but from 2 Taigei that I have (lv1 and lv35), only the former got chosen as subs replacement.

relevant config value:
_SubmarineSwitch_: True
_Area_: 5, _Subarea_: 4
_RetreatLimit_: 2, _RepairLimit_: 2
_RepairTimeLimit_: 0100

**Comment by mrmin123** [comment]
@silfumus I do not have Taigei myself. Could you show me what her entries (lv 1 and 35.. is that Kai?) looks like in the ship selection list?

**Comment by silfumus** [comment]
![20160211_00551734](https://cloud.githubusercontent.com/assets/6127734/12952761/f96cdc0a-d05a-11e5-918e-0dc964d3110d.png)
She's already lv4 because of 5-4 accidental sortie. I think I'll just include her in the expedition fleet for the time being. That way she wouldn't be used as replacement for 5-4 sub fleet.

Let me know if you need anything else, thanks.

**Comment by mrmin123** [comment]
I'll need to implement another check after pressing on what is suspected to be a submarine (Taigei is being selected from the list in the first place because the image matching is done via [this image](https://github.com/mrmin123/kancolle-auto/blob/master/kancolle_auto.sikuli/combat.sikuli/fleetcomp_shiplist_submarine_available.png)). Probably using the AA stat (consistently 0 for subs) in the shiplist-stat screen. I'll get to this later tonight.

Good luck on the event!
