### ISSUE TITLE
SubmarineSwitch auto-bucket

### ISSUE THREAD

**Issue by silfumus** [mrmin123/kancolle-auto#123]
I have 3 sub teams and by using SubmarineSwitch I would save some buckets along the process. But there are certain cases where I don't want the sortie to be paused (i.e: Repair docks fully occupied or said sub (e.g: I-401, U-511) has no duplicates therefore forcing kancolle-auto to repair and pause sortieing).

So, is it possible to have a config option that automatically use bucket if there are no more subs replacement or when the repair docks are almost full?

Or does kancolle-auto already has a combination of config options that I could use to perform those tasks?

**Comment by mrmin123** [comment]
A simple combination of config options to do what you're trying to do doesn't exist, unfortunately.

Slight modification of the Combat module would make enabling buckets when the docks are almost full possible. Changing `if self.repair_time_limit == 0:` in the `go_repair` method of `combat.py` to `if self.repair_time_limit == 0 or empty_docks == 1:` should do it.

The assets and code to use a bucket on a ship already being repaired does not exist at the moment.

`switch_sub` can determine that you don't have any valid subs to swap out, but kancolle_auto has no way of identifying which ship needs to be bucket'ed to be able to get the sortie going again.

Using `FleetcompSwitcher` to swap for the same sortie is possible, but requires more involved changes. Basically you need to make it so that `fleetcomp_switch_action()` in the main `kancolle_auto` loop with the next fleet number whenever deployment is not possible due to repairs/damage (this check is done in the combat module).

**Comment by mrmin123** [comment]
Consolidating ticket into #86 (the FleetcompSwitcher aspect). I'll open another ticket regarding bucketing of ships already under repair if I come up with a way to incorporate that logic.
