### ISSUE TITLE
Expedition resupply loop

### ISSUE THREAD

**Issue by Aftersky** [mrmin123/kancolle-auto#129]
This error is inconsistent and I have no idea what caused it, but it occurs 1-2 times a day. 

One thing I should note is so far it only occurred when fleet 1 is doing 2-3 with subs, I'm not sure if that is a factor though.

Webm: 
https://dl.dropboxusercontent.com/u/73564551/Games/KanColle/resupply.webm

Console log:
https://dl.dropboxusercontent.com/u/73564551/Games/KanColle/expedition%20loop.txt

**Comment by mrmin123** [comment]
Mannnnn that's a really weird one. That webm is really helpful, btw.

In the webm, at 0:18 and 1:07, it goes to switch to fleet 2 in the resupply screen by clicking the fleet 2 flag. Clicking it, however, doesn't actually switch the screen. When it happened at 0:18 I thought it was because it was clicking outside the bounds of the button, but at 1:07 the mouse clearly goes to the middle of the button, but the page still doesn't change over. I can't replicate this in my game, unfortunately, so I can't really debug.

What might work is doing the action to switch fleets twice... in `kancolle_auto.py`, `resupply()`, ~line 134:

```
kc_window.click(pattern_generator(kc_window, fleet_name))
sleep(1)
```

Duplicate the two lines right after so that it's:

```
kc_window.click(pattern_generator(kc_window, fleet_name))
sleep(1)
kc_window.click(pattern_generator(kc_window, fleet_name))
sleep(1)
```

**Comment by Aftersky** [comment]
Yeah it's weird. The script couldn't click on the fleet 2 button in multiple attempts but when I stopped it and takeover, I could switch to fleet 2 just fine. 

I'll try what you suggested and observe it some more, thanks!

**Comment by Aftersky** [comment]
@mrmin123 I received syntax error after duplicating those lines, could you please help me correct it?

```
[error] script stopped with error in line 136 at column 5
[error] SyntaxError ( "mismatched input '' expecting DEDENT",  )
```

**Comment by mrmin123** [comment]
@Aftersky Indentation is important in Python.. could you check that you're not using tabs to indent (use 4 spaces per 'tab' instead) and that the lines are indented the correct amount (20 spaces)?

**Comment by Aftersky** [comment]
Closing this for now since I reverted to older build to avoid other problems, this issue doesn't occur in the older build either.
