### ISSUE TITLE
2-3 Farm Crash

### ISSUE THREAD

**Issue by Danielosama** [mrmin123/kancolle-auto#160]
Hello again,
First of all, I'd like to thank you again for this amazing tool :)
Now, until now I've been using it solely for 3-2A and expeditions, but yesterday I switched to 2-3 Orel cruising with a single sub (Ro-500) and let it work through the night. In the morning I find the script stopped, which never happened ever before :O!
I looked at the log and this happened:

←[94m[2016-04-18 21:59:24] Light damage: 0; moderate damage: 0; critical damage: 1←[0m
[log] CLICK on L(1053,236)@S(0)[0,0 2560x1440]
←[91m[2016-04-18 22:00:07] Non-catbomb script crash, or catbomb script crash w/
unsupported Viewer!←[0m
FindFailed: can not find P(next_alt.png) S: 0.8 T: -86,-125 on the screen.
  Line 1574, in file Region.java

[error] script stopped with error in line 560
[error] FindFailed ( can not find P(next_alt.png) S: 0.8 T: -86,-125 on the screen. )
Exception in thread "main" java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Unknown Source)

I'm going to be honest, I'm too dumb to figure out what's wrong :x
I reckon opening an issue may be overdoing it, but I don't know any other way of asking for help for this tool.
Thanks for the answers,
Daniel.

**Comment by n0k0m3** [comment]
That's... weird. The problem of taiha'd flagship got fixed long ago and ur
problen seems you are using old ver before this fix. However based on ur
log it seems you are using recent ver...
What's your version?
And PLEASE use the template for reporting log so we can troubleshoot your
problem easier.
On Apr 18, 2016 4:34 PM, "Danielosama" notifications@github.com wrote:

Hello again,
First of all, I'd like to thank you again for this amazing tool :)
Now, until now I've been using it solely for 3-2A and expeditions, but
yesterday I switched to 2-3 Orel cruising with a single sub (Ro-500) and
let it work through the night. In the morning I find the script stopped,
which never happened ever before :O!
I looked at the log and this happened:

←[94m[2016-04-18 21:59:24] Light damage: 0; moderate damage: 0; critical
damage: 1←[0m
[log] CLICK on L(1053,236)@S https://github.com/S(0)[0,0 2560x1440]
←[91m[2016-04-18 22:00:07] Non-catbomb script crash, or catbomb script
crash w/
unsupported Viewer!←[0m
FindFailed: can not find P(next_alt.png) S: 0.8 T: -86,-125 on the screen.
Line 1574, in file Region.java

[error] script stopped with error in line 560
[error] FindFailed ( can not find P(next_alt.png) S: 0.8 T: -86,-125 on the
screen. )
Exception in thread "main" java.lang.IllegalStateException: No match found
at java.util.regex.Matcher.group(Unknown Source)

I'm going to be honest, I'm too dumb to figure out what's wrong :x
I reckon opening an issue may be overdoing it, but I don't know any other
way of asking for help for this tool.
Thanks for the answers,
Daniel.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
https://github.com/mrmin123/kancolle-auto/issues/160

**Comment by mrmin123** [comment]
@Danielosama as @minh6a said it seems like you're not necessarily on a more recent version. If you crashed on the flagship retreat screen it is 100% the reason. If your version of kancolle-auto does not have the `combat_flagship_dmg.png`, or make references to that file in `combat.py`, it does not support flagship retreats (which is what happened on your 2-3 run).

I suggest updating to master, as it is fairly stable at the moment.

**Comment by Danielosama** [comment]
That's odd, I'm sure I have the latest version, how do I check that?

**Comment by mrmin123** [comment]
@Danielosama you'll have to remember when you downloaded it or look at the last modified dates of the files... Again, checking to see if the version you're running makes references to `combat_flagship_dmg.png` will help narrow down what could be causing the issue.

Other things that will help is a snippet of the Combat section of your config, what screen kancolle was on when kancolle-auto crashed, and whether or not it consistently occurs (some crashes might be transient and inconsistent).

**Comment by Danielosama** [comment]
I definitely have the latest version since: last modified date is 04/04/16 and combat.py makes reference to combat_flagship_dmg.png.
However, I do have to say that this crash seems to occur at the main screen of the game (your "office" so to say), and this crash happened to me twice, both of them when I did 2-3.

**Comment by mrmin123** [comment]
Does the game behave differently when you only have one ship in your fleet and it gets taiha'ed? As in, does it still go through score screen -> post-battle xp/damage screen -> ship drop (if applicable) -> flagship retreat screen?

**Comment by Danielosama** [comment]
I believe it does yes, let me check that quickly.

**Comment by mrmin123** [comment]
Could you get a screencap of the flagship retreat screen if you do? I'd like to check if it's different from the multi-ship fleet one.

**Comment by Danielosama** [comment]
This is what I get, forgot to mention that my Ro-500 has a reinforcement and carries a repair fairy.

![kancolle-160419-07185542](https://cloud.githubusercontent.com/assets/12687427/14621605/0f6c5b96-05ff-11e6-8fa9-428e5c391937.png)

Edit: this screen appears after the normal cycle: night battle yes/no-> post battle xp->ship drop-> then this.

**Comment by mrmin123** [comment]
Oh, that'll do it... no support for those right now (if ever??) so I'd suggest removing them from your sub.

**Comment by Danielosama** [comment]
Understood, thanks!

**Comment by mrmin123** [comment]
No problem!
