### ISSUE TITLE
Random crashes of script on three screens

### ISSUE THREAD

**Issue by moonlee7777** [mrmin123/kancolle-auto#194]
It tends to mostly crash on the sortie map selection screen, but also on the expedition screen and the refuel screen. I don't think it's a bug, but more a problem with my setup. Here are some things that might help you out: 

![asasas](https://cloud.githubusercontent.com/assets/20227203/16642394/8a8d72c6-43d8-11e6-8cfd-f68806106970.PNG)

[config.zip](https://github.com/mrmin123/kancolle-auto/files/351412/config.zip)

**Comment by mrmin123** [comment]
I would try upping the SleepModifier to 1 or 2.

**Comment by moonlee7777** [comment]
I set it to both 1 and 2 in separate times, but the error is still showing up.

**Comment by mrmin123** [comment]
You'll need to observe kancolle-auto closely and find out what's exactly
happening at the time of a crash. Timing is especially important as
kancolle-auto does not do an `exists` check for the next button. Important
things: what screen? What's on the log? What is the mouse doing before the
crash? What is the log saying right as it happens? Is what the log saying
in line with what is happening on the screen? Is it at a screen where
looking for the next button would make sense? Etc. If kancolle-auto is
crashing because the next button can't be found because the next button
hasn't loaded yet, then you need to adjust the sleep modifier accordingly.

**Comment by moonlee7777** [comment]
Nevermind, it's going smoothly after setting it to 2 for a while. Thank you.

**Comment by mrmin123** [comment]
Cool, closing now.
