### ISSUE TITLE
How did I screw up ? 

### ISSUE THREAD

**Issue by Desoratyr** [mrmin123/kancolle-auto#203]
![test23](https://cloud.githubusercontent.com/assets/20610495/17077188/e510c636-5101-11e6-8270-a672ef94aaec.png)

**Comment by silfumus** [comment]
Restart windows after installing sikuli.

**Comment by Desoratyr** [comment]
![bandicam 2016-07-24 17-01-56-812](https://cloud.githubusercontent.com/assets/20610495/17083829/03bab408-51e7-11e6-8f9e-823ac3b8b228.jpg)
![bandicam 2016-07-24 17-01-59-774](https://cloud.githubusercontent.com/assets/20610495/17083830/03c206e0-51e7-11e6-850a-83e47586acfe.jpg)

Restarted and got something like this

**Comment by mrmin123** [comment]
The warning seems to be due to a bug but doesn't seem to really matter. The fix for it is here: http://stackoverflow.com/questions/16428098/groovy-shell-warning-could-not-open-create-prefs-root-node

The second issue could be due to a malformed `config.ini`. Make sure that it looks like this: https://github.com/mrmin123/kancolle-auto/blob/master/config.ini

Do not delete sections or un-comment lines. The `#` at the beginning of lines are important.

**Comment by Desoratyr** [comment]
![blah](https://cloud.githubusercontent.com/assets/20610495/17089954/b9f3fb60-5266-11e6-8a10-4b981d5b147f.png)

Did I leave something missing in the config. ini ? I checked but there doesn't seem to anything missing though.

**Comment by stackhanovets** [comment]
@Desoratyr,

It seems the script has not seen the browser. Just open Chrome, install KC3Kai, run play window via KC3Kai, open DevTools (Ctrl+Shift+I), select Kancolle, start the game, launch the script and make Chrome window w/ game active again.

**Comment by mrmin123** [comment]
@Desoratyr what @stackhanovets said.. Sikuli is having issues finding your browser. If you have multiple monitors the game/browser needs to be in the first/primary window. That or you're on the wrong Sikuli version.. I think those are the two instances when I've seen the `no attribute 'x'` error message.
