### ISSUE TITLE
Bw4 not starting automatically

### ISSUE THREAD

**Issue by chicken-eater-bay** [mrmin123/kancolle-auto#235]
#### Environment details
- kancolle-auto version (last modified date): Release 5 (2016-08-18)
- Viewer/browser: KCV
- Operating system: Windows 7 SP1
#### Issue

Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)? Please check one of the boxes:
- [x] Consistent
- [ ] Transient

I found out the Bw4: Operation Ro-Go (Sink 50 transport speed) will not start automatically on my observations, kancolle-auto can successfully finds and select Bd5 on the same page but not Bw4.

may i know is there anyway to debug this, for example like how the quests are read?

Thanks

![2016-09-15 05_48_16-kancolleviewer](https://cloud.githubusercontent.com/assets/22205034/18531284/1ce2cc00-7b08-11e6-9c54-dbcb90cdaa5c.png)
#### Relevant config snippet (if applicable)

[Quests]

Enabled: True

Quests: bd1, bd2, bd3, bd4, bd5, bd6, bd7, bd8, bw1, bw2, bw3, bw4, bw5, bw6, bw7, c2, c3, c4, c8, d2, d3, d4, d9, d11, e3, e4

CheckSchedule: 3

**Comment by mrmin123** [comment]
@matsumotokenji I'm honestly not too sure. It might have something to do with the way the quest tree is built within kancolle-auto, but that takes way too long to test, and it needs revising anyway. Maybe after the revision this issue will be fixed.

**Comment by NanjoW** [comment]
Theoretically we should utilize the daily and weekly buttons to make this easier. Might save a lot of API calls in the long run. I have 7 pages of quests so it stepping through all of them is a little overbearing.

**Comment by mrmin123** [comment]
@NanjoW could you tell me what the max length of your daily, weekly, and monthly pages are? I may implement something to utilize those pages but if the savings is only one or two pages I probably won't take this on (I do take PRs!)

@matsumotokenji I found the issue and it's because the tesseract OCR library Sikuli (and by extension kancolle-auto) is using interprets the 400 / 0 / 800 / 0 as 400 / 0 / 500 / 0. Thankfully there's no quest currently with 400 / 0 / 500 / 0 as a quest reward so I'm going to add a fallback quest item to catch it. I'm away from my computer right now, but the fix should be in later tonight (PST).
