### ISSUE TITLE
PvP fleet pre-check failure

### ISSUE THREAD

**Issue by stackhanovets** [mrmin123/kancolle-auto#259]
Hi,

This issue is one of the crucial reasons for the script workflow interruptions while doing 3-2A leveling. 
It usually happens when the fleet has a ship (sub) under repair and there is no _pvp_start_2.png_ on the screen:

![scr](https://cloud.githubusercontent.com/assets/16455270/21563925/21e52570-ce98-11e6-82b3-31785a66848f.png)

As you see, it stuck. My config parts are:

```
[SubmarineSwitch]
Enabled: True
EnabledSubs: all

... 

RetreatLimit: 2
RepairLimit: 1
RepairTimeLimit: 0100
```

However, I do not use _FleetComp_ feature, leaving it 0.

**Comment by mrmin123** [comment]
I can infer what the 'issue' is (not enough console logs), but they're not bugs/behavioral changes I'm going to change:

* You seem to be starting kancolle-auto from the pre-PvP screen. This is an invalid start point for kancolle-auto.
* You have both PvP and Sorties enabled, which is fine. However, if you start the script this way with a ship under-repair in the fleet kancolle-auto will not work because of the PvP sortie failure you saw. Thus: make sure there are no ships under-repair when starting kancolle-auto.
* If started successfully with both PvP and Sorties, it might be entirely possible for the PvP loop to begin with a ship under repair in the fleet (ex: sortie successfully finished, repair started, but could not switch ship out for whatever reason). There are no plans to add an additional repair status check for the PvP module, so I suggest using FleetComps and ensuring that ships you have assigned for PvP and ships you have assigned for Sorties do not overlap. Or make it use buckets every time. There are too many conditions where this can all break otherwise.
