### ISSUE TITLE
Event Support Expeditions not working

### ISSUE THREAD

**Issue by waicool20** [mrmin123/kancolle-auto#286]
#### Environment details

* kancolle-auto version: eb3507e
* Viewer/browser: KC3/Chromium
* Operating system: Linux

#### Issue
Just recently realized this after trying out event configs but it seems that event specific support expeditions are not working. Support fleet is being sent to Expedition 33, instead of the event specific support expedition 205, I checked the code ~~~and there doesn't seem to be anything event specific in the expedition module~~~ Edit: checked again there is, but it's still not sending

#### Relevant config snippet (if applicable)

```
[Expeditions]
Enabled = true
Fleet2 = 38
Fleet3 = 9998
Fleet4 = 5

[Combat]
Enabled = true
FleetComp = 1
Area = E
Subarea = 1-1
CombinedFleet = false
Nodes = 4
NodeSelects = 
Formations = diamond, line_abreast, line_ahead, line_abreast
NightBattles = false, false, true, false
RetreatLimit = 2
RepairLimit = 0
RepairTimeLimit = 100
CheckFatigue = true
PortCheck = true
MedalStop = false
LastNodePush = true

[LBAS]
Enabled = true
EnabledGroups = 1
Group1Nodes = _node_lbas_E-1-B_1, _node_lbas_E-1-B_1
Group2Nodes = 
Group3Nodes = 
```

**Comment by mrmin123** [comment]
lol I was using expeditions to 9998 and 9999 as late as yesterday so I was thinking "that doesn't sound right..." so I was trying to recreate. Successfully navigated to the event screen. Then I realized you're sending to 38 before sending to 9998. I'm betting that when you're already at World 5 for expedition, the highlighted World 5 button is 'close enough' to the Event World button portion being used to match, so it clicks back into World 5, then sends you to expedition 33 since that matches perfectly text-wise.

Try replacing `ensei_area_e.png` with this:

![ensei_area_e](https://cloud.githubusercontent.com/assets/4326866/23005486/76e9d316-f3b1-11e6-9ac4-016ee1c75687.png)

Hopefully this image doesn't collide with the highlighted World 5 button.

**Comment by waicool20** [comment]
Tried it, didn't work

**Comment by mrmin123** [comment]
It doesn't click out of World 5?

I'd just suggest switching your fleets around so that Event expeditions aren't sent out after a World 5 expedition in the interim.

**Comment by waicool20** [comment]
Yeah, I'll try doing that as a workaround for now, but this needs to get ironed out

**Comment by waicool20** [comment]
So apparently it's not because of it being confused by the World 5 icon and event World icon but because since it's already on World 5, it finds the support expedition image and just skips switching worlds all together.

**Comment by mrmin123** [comment]
Makes sense. Thanks for the fix!
