### ISSUE TITLE
Line abreast vs sub-heavy PvP fleets

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#332]
I've figured out how to implement this, but the question is what the cutoff for choosing line abreast vs mixed fleets should be. If there's only one sub in a fleet of 6 it makes more sense to choose line ahead (I think???). Maybe 2+ subs? Or half? Does anyone have any thoughts on this?

**Comment by waicool20** [comment]
I think 1 sub should stick to line ahead, 3 subs should be diamond, then 4+ line abreast.

**Comment by n0k0m3** [comment]
1 sub = double line

**Comment by waicool20** [comment]
@minh6a i dont think the loss in damage potential towards the surface fleet(20%) is worth going double line. Accuracy gain is negligible also since most pvp fleets will be sparkled or neutral fatigue.

I'd rather get an A for failing to get the sub than get a B or below because I failed to damage a few more ships. Besides a single dedicated ASW (sometimes not even) ship is enough to dispatch a single sub even in line ahead.

**Comment by mrmin123** [comment]
Candidate branch is at [331_332_sub_id](https://github.com/mrmin123/kancolle-auto/tree/331_332_sub_id). Also contains changes for #331, #333, and #334. Currently in the middle of testing it myself (I couldn't test PvP changes right now because my PvP matches already occurred).
