### ISSUE TITLE
Keeps checking quest after every sortie

### ISSUE THREAD

**Issue by dice4321** [mrmin123/kancolle-auto#342]
#### Environment details

* kancolle-auto version (date on first line of your CHANGELOG.md): 2017-03-17 Release 9
* Viewer/browser: Google Chrome
* Operating system: Windows 8.1 x64

Config:
http://pastebin.com/A0P8FJfn

#### Issue

The program keeps checking after every sortie, switching subs, even tho its set to 5
also I put 20 into KAGA and its not changing the config file @waicool20

Sick GUI PogChamp

![mdf2r1m](https://cloud.githubusercontent.com/assets/20022859/24077013/cd2804d8-0bfc-11e7-92e2-2140d2afaca5.png)

another instance (after 1 sortie)

![](http://i.imgur.com/3pE0Vz7.png)

**Comment by waicool20** [comment]
@diceman112 Thanks, you may want to press Enter whenever manually entering a number into a spinner element, since the GUI doesn't necessarily register the number immediately without the confirmation. Or you can just give the arrow buttons a few click and it should work.

As for your other problem, might be a one time bug (restart several more times maybe?) since my quests are doing just fine.

**Comment by dice4321** [comment]
oh you were right with the restart, what an odd occurrence. thank yee

**Comment by dice4321** [comment]
Its still happening, if you look thought the logs, it said 5 sorties, go to 4 sorties, and resets back to 5, even tho I set check quest to 20

ctrl+F Next quest check
http://pastebin.com/AEs5GL4m

Could it be, because I disabled pvp the check is always at zero?

**Comment by waicool20** [comment]
Ok the reason why it's always checking quests is because it's always having to recover itself:

```
[log]  TYPE "#ESC."
[2017-03-18 22:04:46] Basic recovery successful! Re-initializing kancolle-auto!
```

When I run into this issue I usually just increase my Sleep Cycle/Modifier bit by bit till it goes away

**Comment by dice4321** [comment]
shieeeet, thank you
