### ISSUE TITLE
How can i change the code so it just resupply only Flagship instead the Fleet?

### ISSUE THREAD

**Issue by yuukoani** [mrmin123/kancolle-auto#347]
*Please read the FAQ/Common Issues section of the README before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kancolle-auto version (date on first line of your CHANGELOG.md):
* Viewer/browser:
* Operating system:

#### Issue
Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)?:

[replace this line with a description of issue, along with any screenshots and/or videos. Please be descriptive as possible, describing step by step what is happening in the game]

#### Console log (if applicable)
```
[replace this line with ~50 lines of console log]
```

#### Relevant config snippet (if applicable)
```
[replace this line with relevant portion from config with comments removed]
```

**Comment by mrmin123** [comment]
Did you figure out how to do this or do you still need help on getting this done?

**Comment by yuukoani** [comment]
Sorry, accidentally closed it. 
I did some edit for the code, but it seems only resupply Flagship before sortieing when i click Run.

When coming back from sortie, it continue sortieing without resupply flagship again. 

Is there anyway to make the code only resupply Flagship? 
Because i decide to level up 1-5.  First node,  6 ships, with preemtive ASW Flagship. 
Normally, Kancolle-Auto will resupply the whole fleet after soriteing, but since only the flagship will do preemtive ASW, there is no need to resupply 5 other ships.

**Comment by mrmin123** [comment]
OK. This is actually going to involve changing code and assets in a few different places.

First of all, you need to generate a new asset for the resupply buttons. You'll need ones to click the checkbox next to the flagship (like `resupply_all.png`), and then a button to click the resupply button. The current implementation doesn't have these because it just clicks the whole-fleet one-click resupply button.

Like so:
![image](https://cloud.githubusercontent.com/assets/4326866/24334706/1a440ad2-1224-11e7-8d1c-9fed05254b67.png) (might need additional cropping; call it `resupply.png`)
![image](https://cloud.githubusercontent.com/assets/4326866/24334707/22790eaa-1224-11e7-8eeb-3e1d75a550f1.png) (call it `resupply_manual_button.png`)
(these images might not work 100% because I captured them via a VNC connection)

You'll then need to specify a custom global region in `util.py`, function `rejigger_mouse`. Going off of the other global regions you need to specify the region like so:
```python
global_regions['flagship_resupply'] = Region(util_settings['game_x'] + 110, util_settings['game_y'] + 156, 25, 25)
```
(The 4 numbers being # of pixels right from upper-left corner of game to where the search box should begin (x coord of upper-right corner of search box), # of pixels down from upper-left corner of game to where the search box should begin (y coord of upper-right corner of search box, width of search box, height of search box, resepectively)

Then you need to update the `resupply` function in `kancolle_auto.py` so that it clicks the resupply checkmark in the previosuly defined flagship_resupply global region (otherwise it might click any of the other 6 resupply buttons) and then click the resupply button:

```python
            if returned:
                # If not resupplying the first fleet, navigate to correct fleet
                if fleet_id != 0:
                    fleet_flag = 'fleet_%d.png' % (fleet_id + 1)
                    fleet_flag_selected = 'fleet_%ds.png' % (fleet_id + 1)
                    while_count = 0
                    while not global_regions['fleet_flags_main'].exists(Pattern(fleet_flag_selected).similar(0.95)):
                        global_regions['fleet_flags_main'].click(pattern_generator(global_regions['fleet_flags_main'], fleet_flag, expand_areas('fleet_id')))
                        sleep_fast()
                        while_count += 1
                        while_count_checker(kc_window, settings, while_count)
                    check_and_click(global_regions['fleet_flags_main'], pattern_generator(global_regions['fleet_flags_main'], Pattern('resupply_all.png').exact()), expand_areas('fleet_id'))
                else:  # THIS IS THE RELEVANT PART
                    check_and_click(global_regions['flagship_resupply'], 'resupply.png')
                    sleep_fast()
                    check_and_click(global_regions['game'], 'resupply_manual_button.png')
                sleep_fast()
```

I think that should work.

**Comment by yuukoani** [comment]
No good. 

It will not sortie and return to supply screen if detects 5 other ships are not fully supplied. 

Can you send me the complete code? I don't know what to do next. It's a headache...

**Comment by mrmin123** [comment]
Comment out these lines in the `Combat` class in `combat.py`, method `pre_sortie_check`:

```python
        if (global_regions['check_resupply'].exists('resupply_alert.png') or global_regions['check_resupply'].exists('resupply_red_alert.png')):
            log_warning("Fleet needs resupply!")
            return False
```

**Comment by yuukoani** [comment]
Thank you! Everything works perfectly. Now i have a cheap leveling method. :D
