### ISSUE TITLE
Logs Question

### ISSUE THREAD

**Issue by Danielosama** [mrmin123/kancolle-auto#358]
So I just came back and realized my lvl 155 Ro-500 is gone..... 
The script was doing expeditions and 3-2A leveling with Ro-500 as tank; this loss is probably my fault as I forgot the cleaning lady would be coming today and I think (?) when she moved around my mouse it messed up the clicking.
I closed the cmd.exe before I knew it and now I don't know if I can check the logs to see what happened, any way to access them?
I'll use less exotic subs from now on :p 

Edit: Btw, now that I'm here, is there any system in place to prevent a fleet from sortieing if it's not 6 ships? Would be useful to prevent further losses if anything goes wrong.

**Comment by waicool20** [comment]
RIP Ro-500, sadly once you close the terminal, everything is lost in history. No such feature but it can be implemented.

On the other hand, seems like saving logs other than crash logs would be a useful feature for KAGA.

**Comment by mrmin123** [comment]
Sorry @Danielosama , just seeing this. Sorry for your Ro-500 loss, my apologies. This honestly could have been due to faulty image matching, since I never really tested with ringed ships before. I'll have to run some checks and re-set thresholds if needed.

And no, no way to re-look at logs after closing the console. Like @waicool20 said maybe it's something that can be outsourced into KAGA. kancolle-auto if run from the command line, technically 'retains' the log on the terminal screen even after a crash/closing the program, as long as you don't close the terminal itself.

It's definitely possible to check for a fixed number of ships on launch, although I'm hesitant to give even more complexity to the config and pre-sortie check code. I'll still give it some thought.

**Comment by waicool20** [comment]
@mrmin123 since you are using Jython you can try leveraging some java libraries like Jackson Json to help parse config files into a POJO to help ease the process, adding a new config option is as simple as adding a new field to your POJO model.

**Comment by Danielosama** [comment]
@mrmin123 Don't worry about it, my new Ro-500 is already lvl 80 :p  (I'll just farm more U-511 next event)
I never had any problem with ringed ships before, but if you can check if there is faulty image matching it'll always help.
