### ISSUE TITLE
Orel night battle

### ISSUE THREAD

**Issue by ghost** [mrmin123/kancolle-auto#367]
i am using the latest version 9.1 and i have question.

i have set my night battle to false and the nodes to default which is 5 for orel. It seems like my subs keep on getting into night battle during the last node of the map. Wondering how to disable that?

**Comment by R-Jimenez** [comment]
Please use the ticket schema next time. <3

Anyways, can you post up the rest of your Orel config?

**Comment by R-Jimenez** [comment]
Please use the ticket schema next time, just for clarity. <3

Anyways, night battle defaults to true for every node, and if you do not specify a setting for the amount of nodes you declared, the script will fill in the blanks. So since you defined 5 possible combat nodes (you only need 3 for orel, but nothing will break with more), your configuration is actually False, True, True, True, True, since you only specified the first node. 

From the wiki:
> NightBattles — Define whether or not to engage in night battle at each combat node, separated by commas. If you specify less values than the number of Nodes, kancolle-auto will automatically use True for the remaining nodes.
>
>Valid values: True to engage in night battle, False to decline night battle; multiple values should be comma-separated
Examples: False if you're running 3-2-A, False, True, True, True, True or just False if you're running 2-3 (Orel Cruising; night battle at everything but 1st node)

**Comment by waicool20** [comment]
Either the above or your boolean value is in lowercase, see similar problem #324 apparently python likes Titlecase booleans
