### ISSUE TITLE
Add/revise assets for 2017 Summer Event 

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#389]
Life support for the 2017 Summer Event!

Same business as usual... provide uncompressed PNG screenshots here, or, if you'd like to generate the assets yourself, please follow the [asset generation guide](https://github.com/mrmin123/kancolle-auto/wiki/Asset-generation-guide).

WIP branch with up-to-date assets: [389_2017_summer_event](https://github.com/mrmin123/kancolle-auto/tree/389_2017_summer_event)

**Comment by eos8012** [comment]
thank you

**Comment by muromachi** [comment]
![second blackboard](https://user-images.githubusercontent.com/25769016/29249533-9c817a86-8063-11e7-8b3a-95876c0f5b9f.png)

![first blackboard](https://user-images.githubusercontent.com/25769016/29249531-98e0de4e-8063-11e7-961d-a9564f306142.png)
Here's what I have, the event selection screens up to E-5 and also the node selects for E-1 J and C node. 
![e1 first select need j](https://user-images.githubusercontent.com/25769016/29249523-8f02dc1a-8063-11e7-9717-ab725996cc3f.png)
![e1 second select need c](https://user-images.githubusercontent.com/25769016/29249526-8f074d54-8063-11e7-99de-2d17f17cafdd.png)
![eos](https://user-images.githubusercontent.com/25769016/29249524-8f06b830-8063-11e7-8c1b-7a5358db5626.png)
![event screen](https://user-images.githubusercontent.com/25769016/29249527-8f0a4b12-8063-11e7-97e3-fbeca5615b3f.png)
![event start](https://user-images.githubusercontent.com/25769016/29249525-8f073ce2-8063-11e7-8c06-39dbe18abaf1.png)

**Comment by waicool20** [comment]
E3 
![image](https://user-images.githubusercontent.com/5538666/29324559-0e83b004-8217-11e7-9b1e-6f06ab4627ec.png)

**Comment by mrmin123** [comment]
@muromachi @waicool20 thanks. WIP branch has been started here: [389_2017_summer_event](https://github.com/mrmin123/kancolle-auto/tree/389_2017_summer_event)

I suspect some of these assets might have to get updated as more maps get unlocked.

**Comment by muromachi** [comment]
E6 screen and boss node LBAS select

![_event_panel_2-2](https://user-images.githubusercontent.com/25769016/29364589-8e03de80-82c6-11e7-95fd-782744b18814.png)
![e6s](https://user-images.githubusercontent.com/25769016/29364594-93d192a8-82c6-11e7-9e4b-822d80821fc9.png)
![e6s1](https://user-images.githubusercontent.com/25769016/29364596-941acf7c-82c6-11e7-9a72-a3c1150c1795.png)

**Comment by muromachi** [comment]
![e7](https://user-images.githubusercontent.com/25769016/29391714-c6189a08-832b-11e7-9cf1-8af1128ef2f8.png)
![e7start](https://user-images.githubusercontent.com/25769016/29391715-c61de4ea-832b-11e7-9666-41bd3e95ab0c.png)
E7

**Comment by yhn147** [comment]
![_event_next_page_1](https://user-images.githubusercontent.com/21001446/29398510-165c375c-8360-11e7-9fbb-1b4957ca4813.png)
_event_next_page_1

![_node_e-1-g](https://user-images.githubusercontent.com/21001446/29398513-165d9ee4-8360-11e7-8fb8-68c870ad1649.png)
_node_e-1-g

![_node_e-1-j](https://user-images.githubusercontent.com/21001446/29398515-165e398a-8360-11e7-9de4-694626987855.png)
_node_e-1-j

![_node_e-3-h](https://user-images.githubusercontent.com/21001446/29398512-165d9822-8360-11e7-9a15-136c0f82fe5f.png)
_node_e-3-h

![_node_e-5-d](https://user-images.githubusercontent.com/21001446/29398511-165d8972-8360-11e7-86ba-650d56b6b431.png)
_node_e-5-d

![_node_e-6-b](https://user-images.githubusercontent.com/21001446/29398514-165e35f2-8360-11e7-89f4-78350ae08761.png)
_node_e-6-b

![_node_lbas_e-4-n_1](https://user-images.githubusercontent.com/21001446/29398581-59d27d66-8360-11e7-91b7-4d3eacf4e198.png)
_node_lbas_e-4-n_1

![_node_lbas_e-4-n_2](https://user-images.githubusercontent.com/21001446/29398548-36967ab4-8360-11e7-8955-7515e8ce24b1.png)
_node_lbas_e-4-n_2

![_node_lbas_e-5-m_1](https://user-images.githubusercontent.com/21001446/29398552-36a9675a-8360-11e7-98a5-e05ffaed7c69.png)
_node_lbas_e-5-m_1

![_node_lbas_e-5-m_2](https://user-images.githubusercontent.com/21001446/29398550-369a512a-8360-11e7-9896-2889a5f511d2.png)
_node_lbas_e-5-m_2

![_node_lbas_e-6-h_1](https://user-images.githubusercontent.com/21001446/29398549-36993f60-8360-11e7-95c2-b7c3f4e54a0a.png)
_node_lbas_e-6-h_1

![_node_lbas_e-6-h_2](https://user-images.githubusercontent.com/21001446/29398551-369a530a-8360-11e7-8d79-8843c8201822.png)
_node_lbas_e-6-h_2

**Comment by muromachi** [comment]
Is there something wrong with how kcauto is reading the node select and LBAS?

Case in point - I'm trying to farm E4 node I. LBAS is set to attack node I twice, I generated the assets _node_lbas_E-4-I_1.png and _node_lbas_E-4-I_2.png myself and they are in the combat.sikuli folder. However, every time I try to sortie I get the following message:

[94m[2017-08-21 21:59:49] Assigning targets to LBAS group 1[0m
[error] Image: Image not valid, but TextSearch is switched off!
[error] RunTimeIDE: Exists: Abort: Jython traceback - current first:
combat (431)
combat (203)
kancolle_auto (240)
kancolle_auto (412)
kancolle_auto (434)
kancolle_auto (540)
[error] RunTimeIDE: ImageMissing:
_node_lbas_E-4-I_1.png
Exception in thread "main"

It is not limited to my self-generated assets - when I was farming E1, I get a very similar ImageMissing error message when it is time to select the choice node (using assets provided in the last update). Maps with no choice nodes or no LBAS used work okay.

Here are the E4 LBAS nodes I used, didn't provide them because they aren't really up to the asset generation guide standards, I think?
![_node_lbas_e-4-i_1](https://user-images.githubusercontent.com/25769016/29522985-e6ddd678-86bd-11e7-8237-ac381c06019d.png)
![_node_lbas_e-4-i_2](https://user-images.githubusercontent.com/25769016/29522986-e6de6732-86bd-11e7-82c2-7ae435c9c27c.png)

**Comment by waicool20** [comment]
@muromachi Either your images are corrupted, or something is wrong with your sikuli install, the script cant read the files in the filesystem

**Comment by perryhuynh** [comment]
It seems `combat_start_lbas.png` is has been changed (at least for the event maps), I don't have World 6 unlocked so I can't check there as well. Here is a screenshot of the new one.

![](http://i.imgur.com/rOxbXma.png)

**Comment by muromachi** [comment]
@waicool20 I reinstalled sikuli, same problem. How would a .png image get corrupted?

I tried running E-1 (has 2 choice nodes), got the error message again:

[92m[2017-08-22 21:46:04] Commencing sortie![0m
[log] CLICK on L(899,595)@S(0)[0,0 1366x768] (525 msec)
[log] CLICK on L(597,356)@S(0)[0,0 1366x768] (538 msec)
[94m[2017-08-22 21:46:15] Spinning compass![0m
[error] Image: could not be loaded: file:/C:/(redacted, this is the path to my kancolle-auto folder)/kancolle_auto.sikuli/quests.sikuli/
_node_E-1-J.png
[error] Image: Image not valid, but TextSearch is switched off!
[error] RunTimeIDE: Exists: Abort: Jython traceback - current first:
util (527)
combat (358)
combat (351)
combat (212)
kancolle_auto (240)
kancolle_auto (412)
kancolle_auto (434)
kancolle_auto (540)
[error] RunTimeIDE: ImageMissing: P(
_node_E-1-J.png -- not valid!) S: 0.8
Exception in thread "main"

I chose to try E1 as well because the E1 assets are provided in the most recent event branch and not self-made. Something else I noticed - the path to the image is in the quests.sikuli, not combat.sikuli folder - but I copied the LBAS images to the quests.sikuli folder as well and still got the same error message,

I can run any other map that has no LBAS or choice nodes, so the rest of the script is working fine,

**Comment by waicool20** [comment]
@muromachi It most definitely is a path problem, jython has issues with non-ascii paths, if you can try moving kancolle-auto to C: root.

OTOH I had this problem earlier on today, turned out that one of the assets i had was missing the `.png` in its filename yet my file explorer showed it as an image correctly somehow... just renamed it correctly and it found the file no problem.

**Comment by waicool20** [comment]
![_node_lbas_E-6-S_1](https://user-images.githubusercontent.com/5538666/29620344-46d16660-8850-11e7-8bb4-b385b85c5756.png)
_node_lbas_E-6-S_1
![_node_lbas_E-6-S_2](https://user-images.githubusercontent.com/5538666/29620343-46700528-8850-11e7-86aa-ded01d197347.png)
_node_lbas_E-6-S_2

**Comment by mrmin123** [comment]
Thanks for the assets guys, I'll try to update the branch tonight.

@muromachi 
> [error] Image: could not be loaded: file:/C:/(redacted, this is the path to my kancolle-auto folder)/kancolle_auto.sikuli/quests.sikuli/

Why is it looking for a node image in quests? Is this the path being searched for LBAS images as well?

**Comment by muromachi** [comment]
@mrmin123 

I have no idea. I reproduced the error messages above, LBAS just says "image not valid" but does not give the exact path.

Things I've tried:
- ensure all images used have the .png extension
- shorten the path to my kancolle-auto folder, it used to be in a folder on my desktop but I placed it in C drive and shortened some of the names (e.g. changing folder name from kancolle_auto to kca) 
- copied all the images used to the quest.sikuli folder -> same error message
- reinstall sikuli 
- reinstall kcauto (I still used a few self-generated assets for LBAS but the E1 assets are those provided in the last branch).

Nothing works, I can run maps without choice or LBAS node ok but when I try to run a map with those I get the two error messages listed above.

**Comment by waicool20** [comment]
Finally got this girl, and good thing you changed the submarine class detection implementation....this girl has AA stats: 
![image](https://user-images.githubusercontent.com/5538666/29645088-b5baaaac-88ad-11e7-8343-a30560ba9071.png)
Luigi Torelli

Will have to add her 2 other forms...but I'm a bit reluctant of remodeling her to IJN(finall) form :/

**Comment by waicool20** [comment]
![_event_panel_2-2](https://user-images.githubusercontent.com/5538666/29747835-885c4c1c-8b39-11e7-9022-b27449989d2d.png)
Current image for E6 wont work after clearing because of the arrow appearing

**Comment by lainconnue** [comment]
But why did script fail at this scene it just keeps going back to home at this scene:
http://imgur.com/a/yq3mj

I stopped the script towards the end because it will just keep repeating the same thing: checking expedition and then reach that particular sortie panel and return to home.

7-08-28 17:46:05)←[0m
←[94m[2017-08-28 15:20:11] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
←[94m[2017-08-28 15:20:22] Going home with 0 or less sidestep(s)!←[0m
[log] CLICK on L(75,344)@S(0)[0,0 1280x768] (520 msec)
←[92m[2017-08-28 15:20:26] At Home!←[0m
←[94m[2017-08-28 15:20:26] Are there returning expeditions to receive?←[0m
←[94m[2017-08-28 15:20:28] No, no fleets to receive!←[0m
←[94m[2017-08-28 15:20:28] Navigating to combat menu with 0 sidestep(s)!←[0m
[log] CLICK on L(162,315)@S(0)[0,0 1280x768] (521 msec)
[log] CLICK on L(291,429)@S(0)[0,0 1280x768] (522 msec)
[log] CLICK on L(750,527)@S(0)[0,0 1280x768] (521 msec)
[log] CLICK on L(203,498)@S(0)[0,0 1280x768] (520 msec)
←[94m[2017-08-28 15:20:47] Resupplying LBAS group 3!←[0m
[log] CLICK on L(749,220)@S(0)[0,0 1280x768] (522 msec)
[log] CLICK on L(289,490)@S(0)[0,0 1280x768] (521 msec)
[log] CLICK on L(740,386)@S(0)[0,0 1280x768] (522 msec)
[log] CLICK on L(634,335)@S(0)[0,0 1280x768] (523 msec)
[log] CLICK on L(740,368)@S(0)[0,0 1280x768] (584 msec)
[log]  TYPE "#ESC."
←[92m[2017-08-28 15:21:10] Basic recovery successful! Re-initializing kancolle-a
uto!←[0m
←[94m[2017-08-28 15:21:10] Reading config file!←[0m
←[94m[2017-08-28 15:21:10] Scheduled Sleep enabled: ~2.0 hours starting at ~0030
←[0m
←[94m[2017-08-28 15:21:10] Expeditions enabled: fleet 2: 5, fleet 3: 21, fleet 4
: 38←[0m
←[94m[2017-08-28 15:21:10] Combat enabled (sortie mode): sortieing to E-2-1←[0m
←[94m[2017-08-28 15:21:10] Submarine Switch enabled←[0m
←[94m[2017-08-28 15:21:10] LBAS enabled: groups 3←[0m
←[94m[2017-08-28 15:21:10] Reading util config file!←[0m
←[92m[2017-08-28 15:21:10] Config successfully loaded!←[0m
←[92m[2017-08-28 15:21:10] Starting kancolle_auto!←[0m
←[94m[2017-08-28 15:21:10] Finding window!←[0m
←[94m[2017-08-28 15:21:10] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
←[94m[2017-08-28 15:21:18] Defining module items!←[0m
←[92m[2017-08-28 15:21:18] Expedition module started←[0m
←[92m[2017-08-28 15:21:18] Combat module started (Sortie mode)←[0m
←[94m[2017-08-28 15:21:18] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
[error] script [ C:\kancolleauto\kancolle-auto-master\kancolle_auto.sikuli ] sto
pped with error in line 540
[error] AttributeError ( 'NoneType' object has no attribute 'setAutoWaitTimeout'
 )
[error] --- Traceback --- error source first
line: module ( function ) statement
50: main (  focus_window )     kc_window.setAutoWaitTimeout(1)
80: main (  go_home )     focus_window()
380: main (  init )     go_home(True)
434: main (  kancolle_auto_wrapper )     init()
540: main (  <module> )     kancolle_auto_wrapper()
[error] --- Traceback --- end --------------

C:\Users\user>java -jar C:\sikulix\sikulix\050417\sikulix.jar -r C:\kancolleauto
\kancolle-auto-master\kancolle_auto.sikuli
←[94m[2017-08-28 15:36:52] Reading config file!←[0m
←[94m[2017-08-28 15:36:52] Scheduled Sleep enabled: ~2.0 hours starting at ~0030
←[0m
←[94m[2017-08-28 15:36:52] Expeditions enabled: fleet 2: 5, fleet 3: 21, fleet 4
: 38←[0m
←[94m[2017-08-28 15:36:52] Combat enabled (sortie mode): sortieing to E-2-1←[0m
←[94m[2017-08-28 15:36:52] Submarine Switch enabled←[0m
←[94m[2017-08-28 15:36:52] LBAS enabled: groups 3←[0m
←[94m[2017-08-28 15:36:52] Reading util config file!←[0m
←[92m[2017-08-28 15:36:52] Config successfully loaded!←[0m
←[92m[2017-08-28 15:36:52] Starting kancolle_auto!←[0m
←[94m[2017-08-28 15:36:52] Finding window!←[0m
←[94m[2017-08-28 15:36:52] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
←[94m[2017-08-28 15:37:00] Defining module items!←[0m
←[92m[2017-08-28 15:37:00] Expedition module started←[0m
←[92m[2017-08-28 15:37:00] Combat module started (Sortie mode)←[0m
←[94m[2017-08-28 15:37:00] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
←[92m[2017-08-28 15:37:08] At Home!←[0m
←[94m[2017-08-28 15:37:08] Checking for returning expeditions!←[0m
←[94m[2017-08-28 15:37:08] Are there returning expeditions to receive?←[0m
←[94m[2017-08-28 15:37:09] No, no fleets to receive!←[0m
←[94m[2017-08-28 15:37:10] Refreshing home with 0 or less sidestep(s)!←[0m
[log] CLICK on L(399,137)@S(0)[0,0 1280x768] (521 msec)
[log] CLICK on L(89,541)@S(0)[0,0 1280x768] (522 msec)
[log]  TYPE "#ESC."
←[92m[2017-08-28 15:37:24] Basic recovery successful! Re-initializing kancolle-a
uto!←[0m
←[94m[2017-08-28 15:37:24] Reading config file!←[0m
←[94m[2017-08-28 15:37:24] Scheduled Sleep enabled: ~2.0 hours starting at ~0030
←[0m
←[94m[2017-08-28 15:37:24] Expeditions enabled: fleet 2: 5, fleet 3: 21, fleet 4
: 38←[0m
←[94m[2017-08-28 15:37:24] Combat enabled (sortie mode): sortieing to E-2-1←[0m
←[94m[2017-08-28 15:37:24] Submarine Switch enabled←[0m
←[94m[2017-08-28 15:37:24] LBAS enabled: groups 3←[0m
←[94m[2017-08-28 15:37:24] Reading util config file!←[0m
←[92m[2017-08-28 15:37:24] Config successfully loaded!←[0m
←[92m[2017-08-28 15:37:24] Starting kancolle_auto!←[0m
←[94m[2017-08-28 15:37:24] Finding window!←[0m
←[94m[2017-08-28 15:37:24] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
←[94m[2017-08-28 15:37:32] Defining module items!←[0m
←[92m[2017-08-28 15:37:32] Expedition module started←[0m
←[92m[2017-08-28 15:37:32] Combat module started (Sortie mode)←[0m
←[94m[2017-08-28 15:37:32] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
←[92m[2017-08-28 15:37:46] At Home!←[0m
←[94m[2017-08-28 15:37:46] Are there returning expeditions to receive?←[0m
←[94m[2017-08-28 15:37:47] No, no fleets to receive!←[0m
←[94m[2017-08-28 15:37:47] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
←[92m[2017-08-28 15:38:00] At Home!←[0m
←[94m[2017-08-28 15:38:00] Are there returning expeditions to receive?←[0m
←[94m[2017-08-28 15:38:01] No, no fleets to receive!←[0m
←[94m[2017-08-28 15:38:05] Let's send fleet 2 out for expedition 5!←[0m
[log]  TYPE "#ESC."
←[92m[2017-08-28 15:38:13] Basic recovery successful! Re-initializing kancolle-a
uto!←[0m
←[94m[2017-08-28 15:38:13] Reading config file!←[0m
←[94m[2017-08-28 15:38:13] Scheduled Sleep enabled: ~2.0 hours starting at ~0030
←[0m
←[94m[2017-08-28 15:38:13] Expeditions enabled: fleet 2: 5, fleet 3: 21, fleet 4
: 38←[0m
←[94m[2017-08-28 15:38:13] Combat enabled (sortie mode): sortieing to E-2-1←[0m
←[94m[2017-08-28 15:38:13] Submarine Switch enabled←[0m
←[94m[2017-08-28 15:38:13] LBAS enabled: groups 3←[0m
←[94m[2017-08-28 15:38:13] Reading util config file!←[0m
←[92m[2017-08-28 15:38:13] Config successfully loaded!←[0m
←[92m[2017-08-28 15:38:13] Starting kancolle_auto!←[0m
←[94m[2017-08-28 15:38:13] Finding window!←[0m
←[94m[2017-08-28 15:38:13] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
←[94m[2017-08-28 15:38:22] Defining module items!←[0m
←[92m[2017-08-28 15:38:22] Expedition module started←[0m
←[92m[2017-08-28 15:38:22] Combat module started (Sortie mode)←[0m
←[94m[2017-08-28 15:38:22] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
←[92m[2017-08-28 15:38:36] At Home!←[0m
←[94m[2017-08-28 15:38:36] Are there returning expeditions to receive?←[0m
←[94m[2017-08-28 15:38:37] No, no fleets to receive!←[0m
←[94m[2017-08-28 15:38:37] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
[log]  TYPE "#ESC."
←[91m[2017-08-28 15:38:45] Non-catbomb script crash, or catbomb script crash w/
unsupported Viewer!←[0m
FindFailed: menu_main_home.png: (12x12) seen at (107, 90) with 1.00 in R[0,0 128
0x736]@S(0) E:Y, T:1.0
  Line 2759, in file Region.java

[error] script [ C:\kancolleauto\kancolle-auto-master\kancolle_auto.sikuli ] sto
pped with error in line 542
[error] FindFailed ( menu_main_home.png: (12x12) seen at (107, 90) with 1.00 in
R[0,0 1280x736]@S(0) E:Y, T:1.0 )
[error] --- Traceback --- error source first
line: module ( function ) statement
70: main (  focus_window )     kc_window.wait(Pattern('menu_main_home.png').exac
t())
80: main (  go_home )     focus_window()
398: main (  init )     go_home()
434: main (  kancolle_auto_wrapper )     init()
540: main (  <module> )     kancolle_auto_wrapper()
[error] --- Traceback --- end --------------

C:\Users\user>^V
'▬' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\user>java -jar C:\sikulix\sikulix\050417\sikulix.jar -r C:\kancolleauto
\kancolle-auto-master\kancolle_auto.sikuli
←[94m[2017-08-28 15:43:11] Reading config file!←[0m
←[94m[2017-08-28 15:43:11] Scheduled Sleep enabled: ~2.0 hours starting at ~0030
←[0m
←[94m[2017-08-28 15:43:11] Expeditions enabled: fleet 2: 5, fleet 3: 21, fleet 4
: 38←[0m
←[94m[2017-08-28 15:43:11] Combat enabled (sortie mode): sortieing to E-2-1←[0m
←[94m[2017-08-28 15:43:11] Submarine Switch enabled←[0m
←[94m[2017-08-28 15:43:11] LBAS enabled: groups 3←[0m
←[94m[2017-08-28 15:43:11] Reading util config file!←[0m
←[92m[2017-08-28 15:43:11] Config successfully loaded!←[0m
←[92m[2017-08-28 15:43:11] Starting kancolle_auto!←[0m
←[94m[2017-08-28 15:43:11] Finding window!←[0m
←[94m[2017-08-28 15:43:11] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
←[94m[2017-08-28 15:43:20] Defining module items!←[0m
←[92m[2017-08-28 15:43:20] Expedition module started←[0m
←[92m[2017-08-28 15:43:20] Combat module started (Sortie mode)←[0m
←[94m[2017-08-28 15:43:20] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
←[92m[2017-08-28 15:43:26] At Home!←[0m
←[94m[2017-08-28 15:43:26] Checking for returning expeditions!←[0m
←[94m[2017-08-28 15:43:26] Are there returning expeditions to receive?←[0m
←[94m[2017-08-28 15:43:27] No, no fleets to receive!←[0m
←[94m[2017-08-28 15:43:28] Refreshing home with 0 or less sidestep(s)!←[0m
[log] CLICK on L(220,199)@S(0)[0,0 1280x768] (526 msec)
[log] CLICK on L(86,368)@S(0)[0,0 1280x768] (521 msec)
←[94m[2017-08-28 15:43:39] Are there returning expeditions to receive?←[0m
←[94m[2017-08-28 15:43:40] No, no fleets to receive!←[0m
←[94m[2017-08-28 15:43:40] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
←[92m[2017-08-28 15:43:47] At Home!←[0m
←[94m[2017-08-28 15:43:47] Checking for returning expeditions!←[0m
←[94m[2017-08-28 15:43:47] Are there returning expeditions to receive?←[0m
←[94m[2017-08-28 15:43:48] No, no fleets to receive!←[0m
←[94m[2017-08-28 15:43:48] Navigating to expedition menu with 0 sidestep(s)!←[0m

[log] CLICK on L(218,335)@S(0)[0,0 1280x768] (522 msec)
[log] CLICK on L(604,211)@S(0)[0,0 1280x768] (521 msec)
←[94m[2017-08-28 15:43:58] Let's send fleet 2 out for expedition 5!←[0m
[log] CLICK on L(287,377)@S(0)[0,0 1280x768] (524 msec)
[log] CLICK on L(642,534)@S(0)[0,0 1280x768] (522 msec)
←[94m[2017-08-28 15:44:04] Trying to send out fleet 2 for expedition 5←[0m
←[94m[2017-08-28 15:44:05] Checking expedition fleet status!←[0m
[log] CLICK on L(588,548)@S(0)[0,0 1280x768] (520 msec)
←[92m[2017-08-28 15:44:09] Expedition sent!: Expedition 5 (ETA 2017-08-28 17:13:
24)←[0m
←[94m[2017-08-28 15:44:20] Let's send fleet 3 out for expedition 21!←[0m
[log] CLICK on L(275,534)@S(0)[0,0 1280x768] (521 msec)
[log] CLICK on L(198,386)@S(0)[0,0 1280x768] (520 msec)
←[94m[2017-08-28 15:44:30] Got valid timer (01:36:14)!←[0m
←[93m[2017-08-28 15:44:30] Expedition is already running: Expedition 21 (ETA 201
7-08-28 17:20:30)←[0m
←[94m[2017-08-28 15:44:34] Let's send fleet 4 out for expedition 38!←[0m
[log] CLICK on L(393,525)@S(0)[0,0 1280x768] (523 msec)
[log] CLICK on L(392,422)@S(0)[0,0 1280x768] (521 msec)
←[93m[2017-08-28 15:44:43] Got invalid timer (02802822.)... trying again!←[0m
←[94m[2017-08-28 15:44:45] Got valid timer (02:02:19)!←[0m
←[93m[2017-08-28 15:44:45] Expedition is already running: Expedition 38 (ETA 201
7-08-28 17:46:45)←[0m
←[94m[2017-08-28 15:44:48] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
←[94m[2017-08-28 15:44:58] Going home with 0 or less sidestep(s)!←[0m
[log] CLICK on L(86,378)@S(0)[0,0 1280x768] (521 msec)
←[92m[2017-08-28 15:45:04] At Home!←[0m
←[94m[2017-08-28 15:45:04] Are there returning expeditions to receive?←[0m
←[94m[2017-08-28 15:45:05] No, no fleets to receive!←[0m
←[94m[2017-08-28 15:45:06] Navigating to combat menu with 0 sidestep(s)!←[0m
[log] CLICK on L(175,333)@S(0)[0,0 1280x768] (523 msec)
[log] CLICK on L(320,366)@S(0)[0,0 1280x768] (521 msec)
[log] CLICK on L(716,526)@S(0)[0,0 1280x768] (524 msec)
[log] CLICK on L(323,487)@S(0)[0,0 1280x768] (524 msec)
←[94m[2017-08-28 15:45:27] Resupplying LBAS group 3!←[0m
[log] CLICK on L(790,217)@S(0)[0,0 1280x768] (525 msec)
[log] CLICK on L(307,497)@S(0)[0,0 1280x768] (522 msec)
[log] CLICK on L(755,363)@S(0)[0,0 1280x768] (520 msec)
[log] CLICK on L(688,324)@S(0)[0,0 1280x768] (521 msec)
[log] CLICK on L(718,280)@S(0)[0,0 1280x768] (524 msec)
[log]  TYPE "#ESC."
←[92m[2017-08-28 15:45:50] Basic recovery successful! Re-initializing kancolle-a
uto!←[0m
←[94m[2017-08-28 15:45:50] Reading config file!←[0m
←[94m[2017-08-28 15:45:50] Scheduled Sleep enabled: ~2.0 hours starting at ~0030
←[0m
←[94m[2017-08-28 15:45:50] Expeditions enabled: fleet 2: 5, fleet 3: 21, fleet 4
: 38←[0m
←[94m[2017-08-28 15:45:50] Combat enabled (sortie mode): sortieing to E-2-1←[0m
←[94m[2017-08-28 15:45:50] Submarine Switch enabled←[0m
←[94m[2017-08-28 15:45:50] LBAS enabled: groups 3←[0m
←[94m[2017-08-28 15:45:50] Reading util config file!←[0m
←[92m[2017-08-28 15:45:50] Config successfully loaded!←[0m
←[92m[2017-08-28 15:45:50] Starting kancolle_auto!←[0m
←[94m[2017-08-28 15:45:50] Finding window!←[0m
←[94m[2017-08-28 15:45:50] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
←[94m[2017-08-28 15:45:57] Defining module items!←[0m
←[92m[2017-08-28 15:45:57] Expedition module started←[0m
←[92m[2017-08-28 15:45:57] Combat module started (Sortie mode)←[0m
←[94m[2017-08-28 15:45:57] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
←[94m[2017-08-28 15:46:08] Going home with 0 or less sidestep(s)!←[0m
[log] CLICK on L(80,327)@S(0)[0,0 1280x768] (523 msec)
[log]  TYPE "#ESC."
←[92m[2017-08-28 15:46:20] Basic recovery successful! Re-initializing kancolle-a
uto!←[0m
←[94m[2017-08-28 15:46:20] Reading config file!←[0m
←[94m[2017-08-28 15:46:20] Scheduled Sleep enabled: ~2.0 hours starting at ~0030
←[0m
←[94m[2017-08-28 15:46:20] Expeditions enabled: fleet 2: 5, fleet 3: 21, fleet 4
: 38←[0m
←[94m[2017-08-28 15:46:20] Combat enabled (sortie mode): sortieing to E-2-1←[0m
←[94m[2017-08-28 15:46:20] Submarine Switch enabled←[0m
←[94m[2017-08-28 15:46:20] LBAS enabled: groups 3←[0m
←[94m[2017-08-28 15:46:20] Reading util config file!←[0m
←[92m[2017-08-28 15:46:20] Config successfully loaded!←[0m
←[92m[2017-08-28 15:46:20] Starting kancolle_auto!←[0m
←[94m[2017-08-28 15:46:20] Finding window!←[0m
←[94m[2017-08-28 15:46:20] Focus on KanColle!←[0m
[log] App.focus:  [5468:Chrome]
[error] Region(-32000,-32000,160,27) outside any screen - subsequent actions mig
ht not work as expected
[error] script [ C:\kancolleauto\kancolle-auto-master\kancolle_auto.sikuli ] sto
pped with error in line 540
[error] java.lang.NullPointerException ( java.lang.NullPointerException )
[error] --- Traceback --- error source first
line: module ( function ) statement
56: main (  focus_window )     while not (kc_window.exists(Pattern('menu_main_ho
me.png').exact()) or
360: main (  init )     focus_window()
434: main (  kancolle_auto_wrapper )     init()
540: main (  <module> )     kancolle_auto_wrapper()
[error] --- Traceback --- end --------------

C:\Users\user>

**Comment by perryhuynh** [comment]
@lainconnue are you on the latest version? That was due to the `combat_start_lbas.png` image being outdated

**Comment by lainconnue** [comment]
@perryhuynh you mean this? 
http://imgur.com/a/KXJfS
The latest zip i downloaded would be kancolle-auto-389_2017_summer_event

**Comment by mrmin123** [comment]
@lainconnue can you run sikuli/kancolle-auto with the `-d 3` flag for the debug messages? That should indicate what is failing.

**Comment by lainconnue** [comment]
http://imgur.com/a/c6Nw3
_event_panel_2-1

**Comment by mrmin123** [comment]
Branch has been updated with newer event panel images.

**Comment by mrmin123** [comment]
Branch has been updated with E-7 node select and LBAS assets.

**Comment by waicool20** [comment]
Assets Ive been using in my farming

_node_lbas_e-4-i_1
![_node_lbas_e-4-i_1](https://user-images.githubusercontent.com/5538666/30012849-7d23817a-9175-11e7-9b7f-74c8bf918673.png)
_node_lbas_e-4-i_2
![_node_lbas_e-4-i_2](https://user-images.githubusercontent.com/5538666/30012851-7d23fa42-9175-11e7-97c8-e4682177dd66.png)
_node_lbas_e-7-g_1
![_node_lbas_e-7-g_1](https://user-images.githubusercontent.com/5538666/30012850-7d23b3a2-9175-11e7-9082-e6d7381f6123.png)
_node_lbas_e-7-g_2
![_node_lbas_e-7-g_2](https://user-images.githubusercontent.com/5538666/30012852-7d242652-9175-11e7-9cd2-e371718fe4bc.png)
_node_lbas_e-7-p_1
![_node_lbas_e-7-p_1](https://user-images.githubusercontent.com/5538666/30012853-7d28db5c-9175-11e7-9a56-98766a87e01b.png)
_node_lbas_e-7-p_2
![_node_lbas_e-7-p_2](https://user-images.githubusercontent.com/5538666/30012854-7d295e60-9175-11e7-8a7c-a1cfb5902082.png)

A bit late but better than never ¯\\\_(ツ)_/¯

**Comment by mrmin123** [comment]
Merging what we have so far into `master`.
