### ISSUE TITLE
How to make my kancolle-auto run faster?

### ISSUE THREAD

**Issue by shiragasama** [mrmin123/kancolle-auto#404]
#### Issue
I can use my kancolle-auto, it seems work fine. But idk why it takes so long to complete a sortie. (see the time log between 2 sortie). And it takes about 3 minutes for a 1-5 node A sortie. Anyway to let it be quicker please?
My current SleepCycle is 1 and Paranoia is 1. JSToffset 2, playing on Chrome with kc3.
Btw, thank you very much for your hardwork, mrmin123!

![capture](https://user-images.githubusercontent.com/32711085/31543526-ad7544fa-b040-11e7-822a-f743a33b5b38.PNG)

**Comment by mrmin123** [comment]
The delay between sorties is because you have PortCheck turned on, which doesn't sortie at all if your base is full, and gives you 15 minutes to empty up ship slots before trying to sortie again.

The delay during combat is a mix of bot overhead (image matching and checking) and the fact that kantai collection loves to waste time so there isn't much that can be done there.

**Comment by shiragasama** [comment]
It worked. Thank you alot (again)!
