### ISSUE TITLE
Repair bug

### ISSUE THREAD

**Issue by wwly23** [mrmin123/kancolle-auto#66]
http://imgur.com/a/G9KwK

IndexError ( list assignment index out of range)
My settings are to always bucket moderately damaged or critically damaged ships if the repair time exceeds 0 hours. It looks like it crashed before it could OCR the time. Sikuli's text reading seems a bit buggy, so I think it would be a good idea to search it using something like this.

http://imgur.com/g2t4g4n
Search "00:" "01:" "02:" "03:", etc.

I think it's cool to have on the expedition since it only does it in the beginning, but not on repairs since they are usually done when we're away from the computer.

Personally since I always bucket I'll edit the script a bit to bypass the timer reading.

**Comment by mrmin123** [comment]
@wwly23 Have you updated kancolle-auto recently? That bug should have been resolved as of 3036514c4d6f7dd0e8e6e4cdaeb0b6fb71fad4a3

**Comment by wwly23** [comment]
I downloaded the script four days ago, so I think I'm up to date.

**Comment by mrmin123** [comment]
One workaround, if set to always use buckets, is implement what you said and skip the OCR entirely. OCRing the entire timer is still necessary, however, when buckets aren't used all the time, since the timer is necessary for determining the next available sortie time. Either way, it sounds like the OCR function needs further expansion and error checking.
