### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by n0k0m3** [mrmin123/kancolle-auto#79]
**Event Memory**
Can you add a feature that can record the event when script execute first time so the script will do exact the same thing next loop?
For example: 
- Choosing map for sortie: I realized every time the script OCR everything from scratch even though the same png(s) appear immediately everytime after clicking, by recording and replay the event, the script can skip OCR-ing and click immediately.
- Choosing expedition: since the code is repetitive and the expedition page is the same all the time, you can save memory and time by skipping OCR after the first run.
- OCR-ing the homepage: The homepage always stay the same unless the expedition fleet returned, so instead of OCR-ing again, why not just obtain the position of all buttons on the first loop?

**Change the png that trigger "next"**
Instead of using the current next.png in both sortie and expedition, the script can use the side bar "FRIEND FLEET AREA" at the bottom-left or "第1艦隊" (1st fleet name) to pre-OCR and click.
This will make the script more complex but it will reduce the time on executing clicks.

**Simplify "formation choosing" event**
Why wasting resource on OCR-ing 4 other formation names while you can just find the "Line-ahead" formation and get the relative position from the button to find 4 others?

P/S: I don't know much about coding and I cannot code any simple program :(( So plz ignore and close the whole issue if they are bs to you :smiley:

**Comment by mrmin123** [comment]
@minh6a Thanks for the feedback.

There are two primary reason why the script re-finds images every time:
1. Sikuli (and as a result, kancolle-auto) has no way of knowing if a click/action was successful without checking for a new image after the click. Many of the actions I've programmed in do constant image-recognition checks so that if a previous click fails and the next expected image does not show up, it will repeat the previous action until expected results are seen.
2. After the discussion regarding bot-detection avoidance (the issue has been deleted by the person who opened it) I implemented random click areas based on image recognition. The reason why I did it via image recognition as opposed to making it a separate action was because of the reason stated above: the script needs to rely on image recognition to progress anyway, so why not implement the random clicks into it?

So for **Event Memory**:
- I'm not sure what you mean by OCR for map sorties. I don't remember any OCR (timer readings) for sorties. Do you mean image recognition? If so, the reason why it OCRs every time is due to the reasons outlined above.
- For expeditions, the only OCR is if an expedition is already running. Subsequent runs do not use OCR (timer readings) for the actions. If you're talking about the image recognition, again, refer to the reasons above.
- See reasons above. Another reason for the image recognition checks is because I wanted to make the script location-independent. No matter where the script finds itself after a long pause, in case of user-interaction, it can find its way back to home.

**Change the png that trigger "next"**
- I actually don't have access to the game at the moment so I'm not sure what 'friend fleet area' you're talking about (I also don't know any Japanese so that probably doesn't help) but the reason for the next button recognition is that if there are any clicks PRIOR to the next button showing up, it's a wasted action. That button is actually the trigger for being able to progress to the next screen.

**Formation selection**
- Again, refer to the reasons at the top of this post.

I personally believe that the long delays due to image recognition and timers are OK because you're 'saving time' by not actually playing the game in the first place by using this script, so a few extra minutes to do everything is fine I think. You could always get around this by removing some of the sleep timers or modifying the rclick() function so that it doesn't try to click a random spot every time, but I'd be wary of that due to the current known bot-detection methods.
