### ISSUE TITLE
Save timing on repair and expedition

### ISSUE THREAD

**Issue by n0k0m3** [mrmin123/kancolle-auto#90]
Repair + Expedition time can be recorded with 1 minute less than OCR results (source: Kancolle wikia - Expedition + Docking thread) => Save (alot) of time (ex: Expe 3 lasts for 20 mins => roughly 70 runs incl resupply and quest accept, save 1 minutes => 3 more runs => 120 additional steel)

**Comment by mrmin123** [comment]
It's a bit late so this is untested but the [90_shorter_timers](https://github.com/mrmin123/kancolle-auto/tree/90_shorter_timers) branch has the shorter timers.

**Comment by n0k0m3** [comment]
Testing:
2+ hrs expeditions: no errors/timing mistakes so far (Tested on 37,38 and 21)
<1.5 hrs expe: the screen refreshes a little bit sooner (1-5 secs) than the timer indicated on KC3Kai plugins but still able to receive return fleets (tested on expe 1,2,3,6) (probably the server offsets is around 1min +_ 5 secs)
Note: Tested on my computer with 100Mbps. Gonna do some testing with ATT 768kbps (regular shtty ADSL speed) soon.

**Comment by mrmin123** [comment]
The OCR results actually only matter for expeditions already underway on script start and repairs. Expeditions started by kancolle-auto have their timers chosen by the `ensei_factory` in the expeditions module, which are hardcoded (a holdover from the original kancolle-auto).

**Comment by mrmin123** [comment]
@minh6a easy to do on your local pull, but I increased the timers created by `ensei_factory` by 5 seconds and pushed to 90_shorter_timers again..

**Comment by mrmin123** [comment]
I am actually going to revert some of the changes from this PR. The original built-in timers are correct, but I think the delay you saw mainly have to do with the fact that kancolle-auto sleeps for 30-45 seconds between each 'cycle.' I'm instead going to move the cycle time into the user config so that the user can specify how often they want kancolle-auto to refresh and check its internal timers. I believe some users prefer longer delays as they believe that it helps avoid bot detection.

**Comment by mrmin123** [comment]
Please change the `SleepCycle` param in `config.ini` to address this from now on.
